[package]
name = "securefs"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = { version = "0.10.3", features = ["aes", "alloc", "std"], default-features = false }
aes-siv = { version = "0.7.0", default-features = false, features = ["alloc", "std"] }
anyhow = "1.0.100"
blake2 = "0.10.6"
ctr = { version = "0.9.2", default-features = false, features = ["alloc", "std"] }
fast32 = "1.0.3"
fuser = { version = "0.16.0", optional = true }
ghash = { version = "0.5.1", default-features = false, features = ["std"] }
log = "0.4.28"
lru = "0.16.2"
parking_lot = "0.12.5"
rand = "0.9.2"
rstest = "0.26.1"
rustix = { version = "1.1.2", features = ["fs", "stdio", "termios"] }
subcase = "0.4.0"
subtle = "2.6.1"
thiserror = "2.0.17"
thread_local = "1.1.9"

[features]
fuse = ["dep:fuser"]

[build-dependencies]
bindgen = "0.72.1"
