[package]
name = "securefs"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = { version = "0.10.3", features = ["aes", "alloc", "std"], default-features = false }
aes-siv = { version = "0.7.0", default-features = false, features = ["alloc", "std"] }
ahash = "0.8.12"
ambassador = "0.4.2"
anyhow = "1.0.100"
blake2 = "0.10.6"
ctr = { version = "0.9.2", default-features = false, features = ["alloc", "std"] }
dashmap = "6.1.0"
env_logger = "0.11.8"
fast32 = "1.0.3"
ghash = { version = "0.5.1", default-features = false, features = ["std"] }
libc = "0.2.177"
log = "0.4.28"
lru = "0.16.2"
ntapi = "0.4.1"
num-bigint = "0.4.6"
once_cell = { version = "1.21.3", features = ["parking_lot"] }
parking_lot = "0.12.5"
protobuf = "3.7.2"
rand = "0.9.2"
rand_chacha = { version = "0.9.0", features = ["os_rng"] }
rusqlite = { version = "0.37.0", default-features = false, features = ["bundled"] }
rustix = { version = "1.1.2", features = ["fs", "stdio", "termios"] }
scopeguard = "1.2.0"
subtle = "2.6.1"
tempfile = "3.23.0"
thiserror = "2.0.17"
thread_local = "1.1.9"
trace = "0.1.7"
winfsp = "0.12.4"

[features]
fuse = [ "dep:bindgen", "dep:pkg-config"]

[dev-dependencies]
tempfile = "3.23.0"
rstest = "0.26.1"
subcase = "0.4.0"

[build-dependencies]
protobuf-codegen = "3.7.2"

[target.'cfg(not(windows))'.build-dependencies]
bindgen = { version = "0.72.1", optional = true }
pkg-config = { version = "0.3.32", optional = true }
