name: Rust CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: cargo test --verbose

      - name: Install fuse3 on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y fuse3 libfuse3-dev

      - name: Run tests with FUSE
        if: runner.os == 'Linux'
        run: cargo test --verbose -F fuse


  test-freebsd:
    name: Test on FreeBSD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Cache cargo dependencies on FreeBSD
        uses: actions/cache@v4
        id: cargo-cache-freebsd
        with:
          path: .cargo-cache
          key: freebsd-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests on FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          envs: 'RUST_BACKTRACE'
          prepare: |
            pkg install -y rust fusefs-libs3 sudo ninja pkgconf cmake llvm
            if ! sudo kldstat -m fusefs > /dev/null 2>&1; then
                sudo kldload fusefs
            fi
            mkdir -p ~/.cargo
            mv ~/freebsd-home/.cargo ~/.cargo || true
          run: |
            cargo test --verbose
            cargo test --verbose -F fuse
            mv ~/.cargo ~/freebsd-home/.cargo || true

